# Generated by Django 5.2.1 on 2025-07-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
